name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/tedsamu/smhi_obs_standalone:latest
          docker run ghcr.io/tedsamu/smhi_obs_standalone:latest
          docker push ghcr.io/tedsamu/smhi_obs_standalone:latest
