name: publish
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the docker image
    run: |
           docker build . --tag ghcr.io/tedsamu/smhi_obs_standalone:latest
           docker run ghcr.io/tedsamu/smhi_obs_standalone:latest
           docker push ghcr.io/tedsamu/smhi_obs_standalone:latest
